# Postgresql version 9.x
#   gem install sqlite3
#
#   Ensure the Postresql gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
      adapter: postgresql
      encoding: SQL_ASCII
      host: localhost
      pool: 5
      username: ubuntu
      password: password1

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
